name: CD

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  packages: write
  id-token: write
  actions: read

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: chmod +x .github/scripts/detect-changes.sh
      - id: set-matrix
        run: .github/scripts/detect-changes.sh

  publish:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.matrix != '[]' }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    strategy:
      matrix:
        component: ${{ fromJson(needs.detect-changes.outputs.matrix).component }}
    steps:
      # Setup
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: cargo-component
      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: wit-bindgen-cli

      # Configure registry
      - run: |
          cat > config.toml << EOF
          default_registry = "ghcr.io"
          [registry."ghcr.io".oci.auth]
          password = "${{ secrets.GH_TOKEN }}"
          username = "wassemble"
          EOF

      # Publish
      - run: |
          cargo component publish -p ${{ matrix.component }} --config config.toml

      # NPM package
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: .github/scripts/publish-npm.sh ${{ matrix.component }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
