name: CD

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: chmod +x .github/scripts/detect-changes.sh
      - id: set-matrix
        run: .github/scripts/detect-changes.sh

  publish:
    needs: detect-changes
    if: ${{ fromJson(needs.detect-changes.outputs.matrix).component != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: ${{ fromJson(needs.detect-changes.outputs.matrix).component }}
    steps:
      # Setup
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall --locked --force cargo-component

      # Configure registry
      - run: |
          cat > config.toml << EOF
          default_registry = "ghcr.io"
          [registry."ghcr.io".oci.auth]
          password = "${{ secrets.GH_TOKEN }}"
          username = "wassemble"
          EOF

      # Publish
      - run: |
          cargo component publish -p ${{ matrix.component }} --config config.toml

      # Make package public
      - run: |
          curl -X PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/orgs/wassemble/packages/container/${{ matrix.component }}/visibility \
            -d '{"visibility":"public"}'
